from classifier import *
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import numpy as np
import sys

train_test_data_file = os.path.join(Data_Dir, 'train_test_data.npz')
LOAD_FROM_DISK = False
if LOAD_FROM_DISK:
    x_train, x_test, y_train, y_test = get_features_and_labels(os.path.join(Data_Dir, 'train'))
    np.savez(train_test_data_file, X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
else:
    npzfile = np.load(train_test_data_file)
    x_train, x_test, y_train, y_test = npzfile['X_train'], npzfile['X_test'], npzfile['y_train'], npzfile['y_test']

batch_size = 64
num_classes = len(classLabels)
epochs = 1500
data_augmentation = True
load_model_weights = True
previous_mode_file = "128features\\weights.450-0.8648.hdf5"

x_train = x_train.reshape((len(x_train), img_rows, img_cols, nchannels))
x_test = x_test.reshape((len(x_test), img_rows, img_cols, nchannels))

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
old_y_train, old_y_test = y_train, y_test
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()

model.add(Conv2D(64, (3, 3), padding='same',
                 input_shape=x_train.shape[1:], kernel_initializer='glorot_uniform'))
model.add(Activation('relu'))
model.add(Conv2D(64, (5, 5), kernel_initializer='glorot_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', kernel_initializer='glorot_uniform'))
model.add(Activation('relu'))
model.add(Conv2D(64, (5, 5), kernel_initializer='glorot_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512, kernel_initializer='glorot_uniform'))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, kernel_initializer='glorot_uniform'))
model.add(Activation('softmax'))
model.summary()

# initiate RMSprop optimizer
#opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)
opt = keras.optimizers.Adadelta(lr=0.1, decay=1e-3)
#opt = keras.optimizers.Adadelta()
#opt = keras.optimizers.Adam(lr=0.0001, decay=1e-6)
#opt = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=1e-5)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy', 'categorical_crossentropy'])

filepath = os.path.join( os.path.join(Data_Dir, "keras_lenet5"), "weights.{epoch:02d}-{val_loss:.4f}.hdf5" )
if not data_augmentation:
    print('Not using data augmentation.')
    if load_model_weights: model.load_weights( os.path.join( os.path.join(Data_Dir, 'keras_lenet5\\back\\'), previous_mode_file) )
    model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              validation_data=(x_test, y_test),
              shuffle=True,
              callbacks=[keras.callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=False, save_weights_only=False, mode='auto', period=10)])
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=180,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=True)  # randomly flip images

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    if load_model_weights: model.load_weights( os.path.join( os.path.join(Data_Dir, 'keras_lenet5\\back\\'), previous_mode_file) )
    steps_per_epoch = x_train.shape[0] // batch_size #x_train.shape[0]#
    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train,
                                     batch_size=batch_size),
                        steps_per_epoch=steps_per_epoch,
                        epochs=epochs,
                        validation_data=(x_test, y_test),
                        callbacks=[keras.callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=False, save_weights_only=False, mode='auto', period=50)],
                        initial_epoch = 500,
                        )#callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0.001, patience=10, verbose=1, mode='auto')])

predicted_prob = model.predict(x_test)
from sklearn import metrics
predicted = np.argmax(predicted_prob, axis=1) 
print(metrics.classification_report(old_y_test, predicted))
print("log-loss = {0:.3f}".format(metrics.log_loss(old_y_test, predicted_prob)))

predictionsFilename = "predictions-4conv-1fc_" + str(img_rows) + "_x_" + str(img_cols) + ".csv"
x_test, filenames = get_feature_test_points(os.path.join(Data_Dir, 'test'))
x_test = x_test.reshape((len(x_test), img_rows, img_cols, nchannels))
predictions = model.predict(x_test)
writePredictionsToCsv(Data_Dir, predictions, filenames)